CREATE TABLE IF NOT EXISTS USUARIO_RESKI (
    ID    SERIAL PRIMARY KEY,
    NOME  VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    CPF   VARCHAR(11)  NOT NULL,
    CONSTRAINT UK_USUARIO_RESKI_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_USUARIO_RESKI_CPF   UNIQUE (CPF)
    );
