CREATE TABLE IF NOT EXISTS TRILHA_RESKI (
    ID          SERIAL PRIMARY KEY,
    STATUS      VARCHAR(100)   NOT NULL,
    CONTEUDO    VARCHAR(4000)  NOT NULL,
    COMPETENCIA VARCHAR(255)   NOT NULL
);