CREATE TABLE IF NOT EXISTS OBJETIVO_RESKI (
    ID        SERIAL PRIMARY KEY,
    CARGO     VARCHAR(150)   NOT NULL,
    AREA      VARCHAR(150)   NOT NULL,
    DESCRICAO VARCHAR(4000)  NOT NULL,
    DEMANDA   VARCHAR(4000)  NOT NULL
);
