-- postgresql

CREATE TABLE IF NOT EXISTS USUARIO_RESKI (
    ID    SERIAL PRIMARY KEY,
    NOME  VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    CPF   VARCHAR(11)  NOT NULL,
    CONSTRAINT UK_USUARIO_RESKI_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_USUARIO_RESKI_CPF   UNIQUE (CPF)
);

CREATE TABLE IF NOT EXISTS TRILHA_RESKI (
    ID          SERIAL PRIMARY KEY,
    STATUS      VARCHAR(100)   NOT NULL,
    CONTEUDO    VARCHAR(4000)  NOT NULL,
    COMPETENCIA VARCHAR(255)   NOT NULL
);

CREATE TABLE IF NOT EXISTS OBJETIVO_RESKI (
    ID        SERIAL PRIMARY KEY,
    CARGO     VARCHAR(150)   NOT NULL,
    AREA      VARCHAR(150)   NOT NULL,
    DESCRICAO VARCHAR(4000)  NOT NULL,
    DEMANDA   VARCHAR(4000)  NOT NULL
);
